<?php

return [
    "kullanicilar" => "Kullanıcılar",
    "kullanici" => "Kullanıcı",
    "personeller" => "Personeller",
    "personel" => "Personel",
    "personel_gruplari" => "Personel Grupları",
    "personel_grubu" => "Personel Grubu",
    "ekle" => "Ekle",
    "duzenle" => "Düzenle",
    "sil" => "Sil",
    "kaydet" => "Kaydet",
    "aktif" => "AKTİF",
    "pasif" => "PASİF",
    "yeni" => "Yeni",
    "yetkiler" => "Yetkiler",
    "yetkileri" => "Yetkileri",
    "goruntule" => "Görüntüle",
    "site_ayarlari" => "Site Ayarları",
    "temel_bilgiler" => "Temel Bilgiler",
    "site_resimleri" => "Site Resimleri",
    "iletisim_bilgileri" => "İletişim Bilgileri",
    "sosyal_medya" => "Sosyal Medya",
    "giris_yap" => "Giriş Yap",
    "profil" => "Profil",
    "yetkiniz_yok" => "Yetkiniz Yok",
    "listesi" => "Listesi",
    "yonetim_paneli" => "Yönetim Paneli",
    "kaydediliyor" => "Kaydediliyor...",
];

